version: "3.9"

services:
  swagger-ui:
    image: swaggerapi/swagger-ui:v3.19.3
    container_name: hourstracker-swagger-ui
    ports:
      - 8079:8080
    environment:
      - API_URL=http://0.0.0.0:8080/api/v1/api-docs/swagger.json
    depends_on:
      - hourstracker

  hourstracker:
    container_name: hourstracker
    ports:
      - 8080:8080
    volumes:
      - ../resources:/opt/resources
    environment:
      IMPORT_FROM: '/opt/resources/import/CSVExport.csv'
      EXPORT_TO: '/opt/resources/export'
      DATABASE_URL: 'postgresql://hourstracker:password@postgresql:5432/hourstracker'
      DATABASE_DRIVER: 'org.postgresql.Driver'
    depends_on:
      postgresql:
        condition: service_started

  postgresql:
    image: bitnami/postgresql
    container_name: hourstracker-postgresql
    ports:
      - "5432:5432"
    volumes:
      - "./data/postgresql:/bitnami/postgresql"
    environment:
      - POSTGRESQL_DATABASE=hourstracker
      - POSTGRESQL_USERNAME=hourstracker
      - POSTGRESQL_PASSWORD=password
