version: "3.9"

services:
  swagger-ui:
    image: swaggerapi/swagger-ui:v3.19.3
    container_name: hourstracker-swagger-ui
    ports:
      - 8079:8080
    environment:
      - API_URL=http://0.0.0.0:8080/api/v1/api-docs/swagger.json
    depends_on:
      - hourstracker

  hourstracker:
    container_name: hourstracker
    ports:
      - 8080:8080
    volumes:
      - ../resources:/opt/resources
    environment:
      IMPORT_FROM: '/opt/resources/import'
      EXPORT_TO: '/opt/resources/export'
      DATABASE_USER: 'hourstracker'
      DATABASE_PASSWORD: 'password'
      DATABASE_URL: 'jdbc:postgresql://postgresql:5432/hourstracker'
      DATABASE_DRIVER: 'org.postgresql.Driver'
    depends_on:
      postgresql:
        condition: service_healthy

  postgresql:
    image: bitnami/postgresql
    container_name: hourstracker-postgresql
    ports:
      - "5432:5432"
    volumes:
      - "./data/postgresql:/bitnami/postgresql"
    environment:
      - POSTGRESQL_DATABASE=hourstracker
      - POSTGRESQL_USERNAME=hourstracker
      - POSTGRESQL_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "sh -c '/opt/bitnami/postgresql/bin/pg_isready -h 0.0.0.0 -p 5432 -d hourstracker -U hourstracker'"]
      interval: 10s
      timeout: 5s
      retries: 5
